name: Access files
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Check the contents of the file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: cat sample.txt
