name: Access files
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Check the contents of the file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cat C:\git0117\sample.txt
